import {StyleSheet} from 'react-native';

export const SWIPE_ACTION_WIDTH = 116;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#111111',
  },
  root: {
    flex: 1,
    backgroundColor: '#111111',
  },
  flex: {
    flex: 1,
  },
  container: {
    padding: 20,
    gap: 16,
    paddingBottom: 120,
  },
  messagesContainer: {
    paddingTop: 12,
    paddingHorizontal: 0,
    gap: 0,
    paddingBottom: 120,
  },
  header: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#2a2a2a',
    backgroundColor: '#111111',
  },
  appBar: {
    minHeight: 56,
    paddingHorizontal: 18,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  appBarTitle: {
    color: '#f2f2f2',
    fontSize: 18,
    fontWeight: '700',
  },
  appBarIconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  appBarSearchWrap: {
    paddingHorizontal: 18,
    paddingBottom: 12,
  },
  appBarSearchField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    backgroundColor: '#1d1d1d',
    borderWidth: 1,
    borderColor: '#2f2f2f',
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  appBarSearchInput: {
    flex: 1,
    color: '#f2f2f2',
    fontSize: 15,
    paddingVertical: 0,
  },
  heroCard: {
    backgroundColor: '#181818',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#2c2c2c',
    gap: 10,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 14,
  },
  heroTitle: {
    color: '#f4f7fb',
    fontSize: 20,
    fontWeight: '800',
  },
  heroText: {
    color: '#b8c7d8',
    fontSize: 14,
    lineHeight: 21,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#2a2a2a',
    backgroundColor: '#0a0a0a',
  },
  sectionTitle: {
    color: '#f5f7fb',
    fontSize: 20,
    fontWeight: '700',
  },
  sectionMetaBanner: {
    color: '#f2f2f2',
    fontSize: 13,
    fontWeight: '600',
  },
  unreadToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  unreadToggleLabel: {
    color: '#d5d5d5',
    fontSize: 12,
    fontWeight: '700',
  },
  swipeRowWrap: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    backgroundColor: '#111111',
  },
  swipeActions: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    zIndex: 0,
  },
  swipeLeftActionWrap: {
    width: SWIPE_ACTION_WIDTH,
    justifyContent: 'center',
    height: '100%',
  },
  swipeRightActionWrap: {
    width: SWIPE_ACTION_WIDTH,
    justifyContent: 'center',
    alignItems: 'flex-end',
    height: '100%',
  },
  swipeActionButton: {
    width: SWIPE_ACTION_WIDTH - 8,
    height: '100%',
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    minHeight: 88,
  },
  swipeActionRead: {
    backgroundColor: '#1f4831',
  },
  swipeActionDelete: {
    backgroundColor: '#58212d',
  },
  swipeActionText: {
    color: '#f4f7fb',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  chatCardShell: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    backgroundColor: '#111111',
  },
  chatCard: {
    flexDirection: 'row',
    gap: 14,
    backgroundColor: '#111111',
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#2a2a2a',
    alignItems: 'center',
  },
  chatAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#2c5f67',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatAvatarText: {
    color: '#f2ffff',
    fontSize: 16,
    fontWeight: '800',
  },
  chatMeta: {
    flex: 1,
    gap: 4,
  },
  chatRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  chatTitle: {
    color: '#f2f2f2',
    fontSize: 17,
    fontWeight: '700',
    flex: 1,
  },
  chatAside: {
    alignItems: 'flex-end',
    gap: 8,
  },
  chatTime: {
    color: '#a0a0a0',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  chatAddress: {
    color: '#9a9a9a',
    fontSize: 14,
  },
  chatSnippet: {
    color: '#cecece',
    fontSize: 14,
    lineHeight: 19,
  },
  chatSnippetUnread: {
    color: '#f4f4f4',
    fontWeight: '700',
  },
  unreadBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    borderRadius: 10,
    backgroundColor: '#3f3f3f',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadBadgeText: {
    color: '#f5f5f5',
    fontSize: 10,
    fontWeight: '800',
  },
  emptyCard: {
    backgroundColor: '#161616',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: '#2a2a2a',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 14,
  },
  emptyTitle: {
    color: '#f4f7fb',
    fontSize: 18,
    fontWeight: '800',
  },
  emptyText: {
    color: '#a6b7c8',
    fontSize: 14,
    lineHeight: 20,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 94,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#5a5a5a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 8},
    elevation: 8,
  },
  fabText: {
    color: '#f7f7f7',
    fontSize: 34,
    lineHeight: 34,
    fontWeight: '300',
    marginTop: -2,
  },
  conversationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#22344d',
  },
  backButton: {
    backgroundColor: '#0e1827',
    borderWidth: 1,
    borderColor: '#27425d',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: '#dff5ff',
    fontWeight: '700',
  },
  conversationHeaderText: {
    flex: 1,
    gap: 2,
  },
  conversationTitle: {
    color: '#f4f7fb',
    fontSize: 20,
    fontWeight: '800',
  },
  conversationSubtitle: {
    color: '#91a7bc',
    fontSize: 13,
  },
  recipientBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#22344d',
  },
  recipientLabel: {
    color: '#79d2ff',
    fontWeight: '800',
    width: 28,
  },
  recipientInput: {
    flex: 1,
    color: '#f4f7fb',
    fontSize: 16,
    borderRadius: 14,
    backgroundColor: '#0d1726',
    borderWidth: 1,
    borderColor: '#22344d',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  messageList: {
    padding: 20,
    gap: 10,
    paddingBottom: 32,
  },
  messageBubble: {
    maxWidth: '82%',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 20,
    gap: 8,
  },
  messageBubbleIncoming: {
    alignSelf: 'flex-start',
    backgroundColor: '#132135',
  },
  messageBubbleOutgoing: {
    alignSelf: 'flex-end',
    backgroundColor: '#79d2ff',
  },
  messageText: {
    fontSize: 15,
    lineHeight: 22,
  },
  messageTextIncoming: {
    color: '#edf6ff',
  },
  messageTextOutgoing: {
    color: '#08111d',
  },
  messageTimestamp: {
    fontSize: 11,
  },
  messageTimestampIncoming: {
    color: '#8fa4b9',
  },
  messageTimestampOutgoing: {
    color: '#18425d',
  },
  messageStatusPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
  },
  messageStatusPillIncoming: {
    backgroundColor: '#19314c',
    borderColor: '#2e4a69',
  },
  messageStatusPillOutgoing: {
    backgroundColor: '#bde7ff',
    borderColor: '#4aa7d8',
  },
  messageStatusPillFailure: {
    backgroundColor: '#ffd5db',
    borderColor: '#d16a7a',
  },
  messageStatusText: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  messageStatusTextIncoming: {
    color: '#dcecff',
  },
  messageStatusTextOutgoing: {
    color: '#114567',
  },
  messageStatusTextFailure: {
    color: '#7c2031',
  },
  messageFailureDetail: {
    fontSize: 12,
    lineHeight: 18,
  },
  messageFailureDetailIncoming: {
    color: '#d7e7f5',
  },
  messageFailureDetailOutgoing: {
    color: '#5c2031',
  },
  composer: {
    padding: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#22344d',
    backgroundColor: '#07101d',
  },
  composerStack: {
    gap: 12,
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
  },
  composerAttachmentWrap: {
    gap: 10,
  },
  composerInput: {
    flex: 1,
    minHeight: 52,
    maxHeight: 120,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#22344d',
    backgroundColor: '#0d1726',
    color: '#f4f7fb',
    paddingHorizontal: 16,
    paddingVertical: 14,
    textAlignVertical: 'top',
  },
  attachButton: {
    backgroundColor: '#182739',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: '#35506f',
  },
  attachButtonText: {
    color: '#dfe8f0',
    fontWeight: '800',
  },
  sendButton: {
    backgroundColor: '#79d2ff',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  sendButtonDisabled: {
    opacity: 0.7,
  },
  sendButtonText: {
    color: '#08111d',
    fontWeight: '800',
  },
  attachmentCard: {
    borderRadius: 16,
    padding: 10,
    gap: 8,
    borderWidth: 1,
  },
  attachmentCardIncoming: {
    backgroundColor: '#0d1726',
    borderColor: '#22344d',
  },
  attachmentCardOutgoing: {
    backgroundColor: '#bfe8ff',
    borderColor: '#79d2ff',
  },
  attachmentPreviewImage: {
    width: 180,
    height: 140,
    borderRadius: 12,
    backgroundColor: '#09111b',
  },
  attachmentTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentTitleIncoming: {
    color: '#f0f5fb',
  },
  attachmentTitleOutgoing: {
    color: '#08111d',
  },
  attachmentMeta: {
    fontSize: 12,
  },
  attachmentMetaIncoming: {
    color: '#9fb0c2',
  },
  attachmentMetaOutgoing: {
    color: '#24506d',
  },
  attachmentRemoveButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#182739',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  attachmentWarningText: {
    color: '#f6bd60',
    fontSize: 12,
    lineHeight: 18,
  },
  attachmentRemoveButtonText: {
    color: '#dfe8f0',
    fontWeight: '700',
    fontSize: 12,
  },
  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 18,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#2a2a2a',
    backgroundColor: '#111111',
  },
  bottomTab: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  bottomTabText: {
    color: '#7f97ac',
    fontSize: 12,
    fontWeight: '700',
  },
  bottomTabTextActive: {
    color: '#79d2ff',
    fontSize: 12,
    fontWeight: '800',
  },
  iconBubble: {
    width: 24,
    height: 20,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  iconBubbleBody: {
    width: 20,
    height: 15,
    borderRadius: 7,
    borderWidth: 1.6,
    borderColor: '#7f97ac',
  },
  iconBubbleTail: {
    width: 7,
    height: 7,
    marginTop: -2,
    marginLeft: 3,
    borderLeftWidth: 1.6,
    borderBottomWidth: 1.6,
    borderColor: '#7f97ac',
    transform: [{skewX: '-18deg'}],
  },
  iconActiveFill: {
    backgroundColor: '#79d2ff',
  },
  iconBubbleBodyActive: {
    borderColor: '#79d2ff',
  },
  iconBubbleTailActive: {
    borderColor: '#79d2ff',
  },
  iconStack: {
    width: 24,
    gap: 3,
    alignItems: 'flex-start',
  },
  iconStackDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#7f97ac',
  },
  iconStackLine: {
    width: 20,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#7f97ac',
  },
  iconStackLineShort: {
    width: 14,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#7f97ac',
  },
  iconPhone: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconPhoneArc: {
    width: 18,
    height: 10,
    borderRadius: 8,
    backgroundColor: '#7f97ac',
    transform: [{rotate: '-35deg'}],
  },
  iconPhoneHandle: {
    position: 'absolute',
    width: 7,
    height: 16,
    borderRadius: 5,
    backgroundColor: '#7f97ac',
    transform: [{rotate: '-35deg'}, {translateX: 4}, {translateY: 1}],
  },
  iconDialer: {
    width: 22,
    height: 22,
    justifyContent: 'space-between',
  },
  iconDialerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconDialerDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#7f97ac',
  },
  searchIconWrap: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchIconWrapCompact: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchLens: {
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 1.6,
    borderColor: '#d0d0d0',
  },
  searchLensCompact: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.6,
    borderColor: '#d0d0d0',
  },
  searchHandle: {
    width: 7,
    height: 1.6,
    borderRadius: 1,
    backgroundColor: '#d0d0d0',
    transform: [{rotate: '45deg'}, {translateX: 5}, {translateY: -1}],
  },
  searchHandleCompact: {
    width: 6,
    height: 1.6,
    borderRadius: 1,
    backgroundColor: '#d0d0d0',
    transform: [{rotate: '45deg'}, {translateX: 4}, {translateY: -1}],
  },
  closeIconWrap: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeIconLine: {
    position: 'absolute',
    width: 16,
    height: 1.8,
    borderRadius: 1,
    backgroundColor: '#d0d0d0',
  },
  closeIconLineForward: {
    transform: [{rotate: '45deg'}],
  },
  closeIconLineBackward: {
    transform: [{rotate: '-45deg'}],
  },
  card: {
    backgroundColor: '#111c2e',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#22344d',
    gap: 12,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  label: {
    color: '#dfe8f0',
    fontSize: 14,
    fontWeight: '600',
  },
  statusText: {
    color: '#7ae582',
    fontSize: 14,
    fontWeight: '700',
  },
  statusTextStopped: {
    color: '#f6bd60',
  },
  statusTextPending: {
    color: '#79d2ff',
  },
  detailText: {
    color: '#9fb0c2',
    fontSize: 13,
    lineHeight: 20,
  },
  checklistItem: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  checklistLabel: {
    color: '#dfe8f0',
    fontSize: 14,
  },
  ready: {
    color: '#7ae582',
    fontSize: 11,
    fontWeight: '800',
    width: 56,
  },
  notReady: {
    color: '#f6bd60',
    fontSize: 11,
    fontWeight: '800',
    width: 56,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  button: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  buttonPrimary: {
    backgroundColor: '#7fc8f8',
  },
  buttonSecondary: {
    backgroundColor: '#182739',
    borderWidth: 1,
    borderColor: '#35506f',
  },
  buttonTextPrimary: {
    color: '#08111d',
    fontWeight: '800',
  },
  buttonTextSecondary: {
    color: '#dfe8f0',
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonTextDisabled: {
    opacity: 0.75,
  },
  inputGroup: {
    gap: 6,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#35506f',
    backgroundColor: '#0d1726',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#f5f7fb',
  },
  inputDisabled: {
    opacity: 0.55,
  },
  eventRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#22344d',
    paddingTop: 12,
    gap: 4,
  },
  eventType: {
    color: '#7fc8f8',
    fontWeight: '700',
  },
  eventTime: {
    color: '#9fb0c2',
    fontSize: 12,
  },
  eventPayload: {
    color: '#dfe8f0',
    fontSize: 12,
  },
  dialPad: {
    gap: 10,
  },
  dialPadRow: {
    flexDirection: 'row',
    gap: 10,
  },
  dialPadKey: {
    flex: 1,
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: '#0d1726',
    borderWidth: 1,
    borderColor: '#35506f',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialPadKeyText: {
    color: '#f5f7fb',
    fontSize: 24,
    fontWeight: '700',
  },
  callCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#22344d',
    backgroundColor: '#0d1726',
    padding: 14,
    gap: 12,
  },
  callCardHeader: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  callCardTitle: {
    color: '#f4f7fb',
    fontSize: 16,
    fontWeight: '800',
  },
  callMutePill: {
    color: '#08111d',
    backgroundColor: '#79d2ff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
  },
  recentCallRow: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#22344d',
    backgroundColor: '#0d1726',
    padding: 14,
    gap: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  recentCallUse: {
    color: '#79d2ff',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
});
